#!/usr/bin/env node
/**
 * ApexPanda Headless 节点客户端
 * 用法: apexpanda-node run --gateway http://localhost:18790 --display-name "Build Node"
 */
import { randomUUID } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, dirname, resolve } from 'node:path';
import { platform } from 'node:os';
import { fileURLToPath } from 'node:url';
import { createNodeClient } from './client.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const isWindows = platform() === 'win32';
const PM2_APP_NAME = 'apexpanda-node';

function getDataDir(): string {
  const base = process.env.APEXPANDA_DATA_DIR ?? join(process.env.HOME ?? process.env.USERPROFILE ?? process.cwd(), '.apexpanda');
  return base;
}

function getNodeConfigPath(): string {
  return join(getDataDir(), 'node.json');
}

interface NodeConfig {
  deviceId?: string;
  token?: string;
  displayName?: string;
  gatewayUrl?: string;
}

async function loadNodeConfig(): Promise<NodeConfig> {
  try {
    const raw = await readFile(getNodeConfigPath(), 'utf-8');
    return JSON.parse(raw) as NodeConfig;
  } catch {
    return {};
  }
}

async function saveNodeConfig(cfg: NodeConfig): Promise<void> {
  await mkdir(getDataDir(), { recursive: true });
  await writeFile(getNodeConfigPath(), JSON.stringify(cfg, null, 2), 'utf-8');
}

async function run(args: { gateway: string; displayName: string }) {
  const gatewayUrl = args.gateway || process.env.APEXPANDA_GATEWAY_URL || 'http://127.0.0.1:18790';
  const displayName = args.displayName || process.env.APEXPANDA_NODE_DISPLAY_NAME || 'Headless Node';

  let cfg = await loadNodeConfig();
  if (!cfg.deviceId) {
    cfg.deviceId = randomUUID();
    await saveNodeConfig(cfg);
  }
  await saveNodeConfig({ ...cfg, gatewayUrl, displayName });

  const token = process.env.APEXPANDA_NODE_TOKEN || cfg.token;
  // 语义化平台：headless=无界面服务器节点，供 nodePlatform 过滤（linux/ifconfig 等）
  const platformName = 'headless';
  console.log('[apexpanda-node] Connecting to', gatewayUrl);
  console.log('[apexpanda-node] Device ID:', cfg.deviceId);
  if (!token) {
    console.log('[apexpanda-node] No token - first run. Approve at Gateway Dashboard or API:');
    console.log('  POST /api/v1/nodes/pending/<requestId>/approve');
    console.log('[apexpanda-node] After approval, store the token in', getNodeConfigPath());
  }
  createNodeClient({
    gatewayUrl,
    token,
    deviceId: cfg.deviceId!,
    displayName,
    platform: platformName,
    onPaired: async (nodeId, token) => {
      console.log('[apexpanda-node] Paired! nodeId:', nodeId);
      await saveNodeConfig({ ...cfg, token });
      cfg = { ...cfg, token };
    },
  });

  process.on('SIGINT', () => process.exit(0));
  process.on('SIGTERM', () => process.exit(0));
}

function getEcosystemPath(): string {
  return join(getDataDir(), 'ecosystem.config.cjs');
}

function getSystemdUnitPath(): string {
  return join(process.env.HOME ?? '', '.config', 'systemd', 'user', 'apexpanda-node.service');
}

async function installService(args: { gateway: string; displayName: string }) {
  const gatewayUrl = args.gateway || process.env.APEXPANDA_GATEWAY_URL || 'http://127.0.0.1:18790';
  const displayName = args.displayName || process.env.APEXPANDA_NODE_DISPLAY_NAME || 'Headless Node';

  let cfg = await loadNodeConfig();
  if (!cfg.deviceId) {
    cfg.deviceId = randomUUID();
    await saveNodeConfig(cfg);
  }
  cfg = { ...cfg, gatewayUrl, displayName };
  await saveNodeConfig(cfg);

  const scriptPath = resolve(__dirname, 'index.js');
  const ecosystemPath = getEcosystemPath();
  await mkdir(getDataDir(), { recursive: true });

  const ecosystemContent = `/** pm2 ecosystem - generated by apexpanda-node install */
module.exports = {
  apps: [{
    name: '${PM2_APP_NAME}',
    script: '${scriptPath.replace(/\\/g, '\\\\')}',
    args: 'run',
    cwd: '${dirname(scriptPath).replace(/\\/g, '\\\\')}',
    env: {
      APEXPANDA_GATEWAY_URL: '${gatewayUrl}',
      APEXPANDA_NODE_DISPLAY_NAME: '${displayName}',
    },
  }],
};
`;
  await writeFile(ecosystemPath, ecosystemContent, 'utf-8');
  console.log('[apexpanda-node] Created', ecosystemPath);

  if (!isWindows && process.env.HOME) {
    const systemdDir = join(process.env.HOME, '.config', 'systemd', 'user');
    await mkdir(systemdDir, { recursive: true });
    const unitPath = getSystemdUnitPath();
    const unitContent = `[Unit]
Description=ApexPanda Headless Node
After=network.target

[Service]
Type=simple
ExecStart=${process.execPath} ${scriptPath} run
Environment=APEXPANDA_GATEWAY_URL=${gatewayUrl}
Environment=APEXPANDA_NODE_DISPLAY_NAME=${displayName}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
`;
    await writeFile(unitPath, unitContent, 'utf-8');
    console.log('[apexpanda-node] Created systemd user unit:', unitPath);
    console.log('  Enable: systemctl --user enable apexpanda-node');
    console.log('  Start:  systemctl --user start apexpanda-node');
  }

  console.log('');
  console.log('Start with pm2:');
  console.log('  pm2 start', ecosystemPath);
  console.log('  pm2 save && pm2 startup   # persist across reboot');
}

async function pm2Command(sub: string, extraArgs: string[] = []): Promise<boolean> {
  const { spawn } = await import('node:child_process');
  return new Promise((resolve) => {
    const proc = spawn('pm2', [sub, PM2_APP_NAME, ...extraArgs], {
      stdio: 'inherit',
      shell: isWindows,
    });
    proc.on('close', (code) => resolve(code === 0));
  });
}

async function startService() {
  const ecosystemPath = getEcosystemPath();
  try {
    await readFile(ecosystemPath);
  } catch {
    console.error('[apexpanda-node] Not installed. Run: apexpanda-node install --gateway <url>');
    process.exit(1);
  }
  const { spawn } = await import('node:child_process');
  const ok = await new Promise<boolean>((resolve) => {
    const proc = spawn('pm2', ['start', ecosystemPath], {
      stdio: 'inherit',
      shell: isWindows,
    });
    proc.on('close', (code) => resolve(code === 0));
  });
  if (!ok) {
    console.error('[apexpanda-node] pm2 start failed. Is pm2 installed? npm i -g pm2');
    process.exit(1);
  }
}

async function stopService() {
  const ok = await pm2Command('stop');
  if (!ok) {
    console.error('[apexpanda-node] pm2 stop failed. Is pm2 installed?');
    process.exit(1);
  }
}

async function statusService() {
  const { spawn } = await import('node:child_process');
  const proc = spawn('pm2', ['show', PM2_APP_NAME], { stdio: 'inherit', shell: isWindows });
  proc.on('close', (code) => process.exit(code ?? 1));
}

async function initExecApprovals() {
  const { writeFile } = await import('node:fs/promises');
  const path = join(getDataDir(), 'exec-approvals.json');
  const sample = {
    mode: 'full',
    rules: [],
    _comment: 'mode: full=全部允许, blacklist=黑名单禁止, remote-approve=需Dashboard审批; rules仅blacklist时生效',
  };
  await writeFile(path, JSON.stringify(sample, null, 2), 'utf-8');
  console.log('[apexpanda-node] Created', path);
}

async function main() {
  const argv = process.argv.slice(2);
  const cmd = argv[0] ?? 'run';

  if (cmd === 'init') {
    await initExecApprovals();
    return;
  }

  if (cmd === 'run') {
    let gateway = 'http://127.0.0.1:18790';
    let displayName = 'Headless Node';
    for (let i = 1; i < argv.length; i++) {
      if (argv[i] === '--gateway' && argv[i + 1]) {
        gateway = argv[++i];
      } else if (argv[i] === '--display-name' && argv[i + 1]) {
        displayName = argv[++i];
      }
    }
    await run({ gateway, displayName });
  } else if (cmd === 'install') {
    let gateway = process.env.APEXPANDA_GATEWAY_URL || 'http://127.0.0.1:18790';
    let displayName = process.env.APEXPANDA_NODE_DISPLAY_NAME || 'Headless Node';
    for (let i = 1; i < argv.length; i++) {
      if (argv[i] === '--gateway' && argv[i + 1]) gateway = argv[++i];
      else if (argv[i] === '--display-name' && argv[i + 1]) displayName = argv[++i];
    }
    await installService({ gateway, displayName });
  } else if (cmd === 'start') {
    await startService();
  } else if (cmd === 'stop') {
    await stopService();
  } else if (cmd === 'status') {
    await statusService();
  } else if (cmd === '--help' || cmd === '-h' || cmd === 'help') {
    console.log(`
ApexPanda Headless Node Client

Usage:
  apexpanda-node run [options]        Run in foreground
  apexpanda-node install [options]    Create pm2/systemd config for background service
  apexpanda-node start                Start via pm2 (requires: npm i -g pm2)
  apexpanda-node stop                 Stop pm2 process
  apexpanda-node status               Show pm2 status
  apexpanda-node init                 Create ~/.apexpanda/exec-approvals.json (default mode: full)

Options (run, install):
  --gateway <url>       Gateway URL (default: http://127.0.0.1:18790)
  --display-name <name> Display name for this node

Examples:
  apexpanda-node run --gateway http://localhost:18790
  apexpanda-node install --gateway http://gateway.example.com:18790
  pm2 start ~/.apexpanda/ecosystem.config.cjs

Environment:
  APEXPANDA_GATEWAY_URL    Gateway URL
  APEXPANDA_NODE_TOKEN     Token (after pairing, or set in node.json)
  APEXPANDA_DATA_DIR       Data directory (default: ~/.apexpanda)
  APEXPANDA_EXEC_MODE      full | blacklist | remote-approve
`);
  } else {
    console.error('Unknown command:', cmd);
    process.exit(1);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
